;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        +multiple-cursors/evil-mc-toggle-cursor-here
        counsel-M-x
        doom/backward-to-bol-or-indent
        eri-indent
        evil-delete-back-to-indentation
        evil-delete-backward-char-and-join
        evil-escape
        evil-exit-emacs-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-org-delete
        lean-tab-indent
        markdown-outdent-or-delete
        org-cycle
        ))

(setq mc/cmds-to-run-once
      '(
        evil-normal-state
        mouse-set-region
        org-delete-char
        org-self-insert-command
        undo-fu-only-undo
        ))
