;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        +multiple-cursors/evil-mc-toggle-cursor-here
        TeX-insert-backslash
        agda2-load
        counsel-M-x
        doom/backward-to-bol-or-indent
        doom/forward-to-last-non-comment-or-eol
        drag-stuff-down
        drag-stuff-left
        drag-stuff-right
        drag-stuff-up
        eri-indent
        evil-delete
        evil-delete-back-to-indentation
        evil-delete-backward-char-and-join
        evil-delete-char
        evil-escape
        evil-exit-emacs-state
        evil-forward-char
        evil-forward-word-begin
        evil-insert
        evil-next-line
        evil-org-delete
        evil-previous-line
        evil-window-left
        evilnc-comment-or-uncomment-lines
        indent-for-tab-command
        lean-tab-indent
        markdown-cycle
        markdown-outdent-or-delete
        org-cycle
        org-yank
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        +snippets/delete-forward-char-or-field
        agda2-goal-and-context-and-checked
        evil-backward-char
        evil-ex-search-next
        evil-mouse-drag-region
        evil-normal-state
        evil-visual-char
        mouse-set-region
        org-delete-char
        org-self-insert-command
        overwrite-mode
        undo-fu-only-undo
        ))
